-- This is GOB game config file, allegro ini files is too simple for this task
-- 

Stars = {
	{
		name="GOB Star",
		x   = "10",
		y   = "10",
		suns = { {name="Gob Star", x = "12000", y = "12000", sprite="vanguard.dat#Star000"}},
		planets = {
			{name="GOB 1", x= "?", y = "?" },
			{name="GOB 2", x= "?", y = "?" },
			{name="GOB 3", x= "?", y = "?" },
			{name="GOB 4", x= "?", y = "?" }
		},
		starbases = {
			{name="Supox", 
			 x = "?", y = "?", 
			 buildtype      = "supbl", 
			 commander      = "gamedata/supox_station.lua", 
			 orbit          = "GOB 1", 
			 sprite         = "gob.dat#station0sprite",
			 background     = "gob.dat#station0picture.bmp"
		    },
			{name="Orz", 
			 x = "?", y = "?", 
			 buildtype="orzne", 
			 commander="gamedata/orz_station.lua", 
			 orbit="GOB 2", 
			 sprite = "gob.dat#station1sprite",
			 background     = "gob.dat#station1picture.bmp"
		    },
			{name="Kohr-Ah", 
			 x = "?", y = "?", 
			 buildtype="kohma", 
			 commander="gamedata/korah_station.lua", 
			 orbit="GOB 3", 
			 sprite = "gob.dat#station2sprite",
			 background     = "gob.dat#station2picture.bmp"
		    },
			{name="Utwig", 
			 x = "?", y = "?", 
			 buildtype="utwju", 
			 commander="gamedata/utwig_station.lua", 
			 orbit="GOB 4", 
			 sprite = "gob.dat#station2sprite",
			 background     = "gob.dat#station2picture.bmp"
		    }
		}
	}
}

------------------------------------------------------------------------------
-- Main file with the definitions of all the service functions used by      --
-- other scripts.                                                           --
--                                                                          --
-- DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!                --
------------------------------------------------------------------------------

function InitSuns( suns )
	for a, b in suns do
		AddSun (b.name, b.x, b.y );
	end
end

function InitPlanets( planets )
	for a, b in planets do
		AddPlanet (b.name, b.x, b.y );
	end
end
	
function InitSpaceStations ( stations )
	for a, b in stations do
		AddStation (b.name, b.x, b.y, b.buildtype, b.commander, b. orbit, b.sprite, b.background )
	end
end
function InitStarSystem ()
	for a, b in Stars do
		if b.name == "GOB Star" then
			InitSuns(b.suns);
			InitPlanets( b.planets );
			InitSpaceStations(b.starbases);
		end
	end
end

InitStarSystem();

