[Network]
;Prediction = 100 GEO about prediction: buggy annoying and inadequate
Prediction = 0
Port = 15515
Address = 11.1.1.1
NetworkMeleeUseTeams = 0
OptimizeLatency = 1

GameName = Melee
Nhumans = 3
Nbots = 3

[System]
AutoUnload = 1

[Video]
ScreenWidth = 800
ScreenHeight = 600

BitsPerPixel = 32
;valid = values are 8 (ugly), 15, 16, 24 (slow), and 32

FullScreen = 2
; = 0 = windowed, 1 = fullscreen

Gamma = 45
;gamma = gamma correction, should be between 0 and 255



[Sound]

SoundOn = 2
MusicOn = 2
SoundVolume = 138
MusicVolume = 137
Music = melee.dat#MELEEMUS_MOD
;melee.dat = #PLANETMUSIC_MOD , #MELEEMUS_MOD


[View]
View = Enemy
;determines = where the camera goes
InterpolateFrames = 0
;0 = low quality, 1 = high quality
Mip_min = 0
;from = 0 to 3?  0 = normal, 1 = low quality, 2 = very low quality, ...
Mip_max = 10
;from = 0 to 3?  0 = high quality, 99 = normal
Mip_bias = 0
;from = -3? to 3?  0 = normal, -1 = high quality, 1 = low quality, 2 = very low quality
;(Hero, = Enemy, Enemy_Discrete, Split, Everything)
MinimumFrameRate = 15.0
; = determines the worst-case frameskipping (between 5 and 15 recommended)
FPS_Time = 250
; = milliseconds per time the FPS is updated.

Key_zoomin = EQUALS
Key_zoomout = MINUS
Key_alter1 = 0
Key_alter2 = 9


[Rendering]
AA_Mode = 32768


[Stars]
quality = 5
;recomended = quality settings are 1, 2, and 5


[Gob]
NumPlayers = 1


[Menu]
skin = interfaces/gametest
SelectGame = 7

